# Check https://github.com/londonmedicallaboratory/api-sdk for latest configuration options
framework:
    cache:
        pools:
            view_cache_pool:    # default pool name; use redis if possible
                tags: true      # adapter must allow tagging items

lml_sdk:
    base_url: 'base_url_or_env'
    api_token: 'api_token_value_or_env'
    cache_pool: cache.app       # use default cache pool or create your own
    cache_expiration: 3600
    faker: false
