name: Static analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.0'
          coverage: none
          extensions: mbstring, intl
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download dependencies
        run: composer install --no-interaction --no-progress --ignore-platform-reqs

      - name: Execute Psalm
        run: vendor/bin/psalm --no-progress 
